### ISSUE TITLE
Game and Watch logo is invisible

### ISSUE THREAD

**Issue by bmn001** [RetroPie/es-theme-carbon-2021#7]
The Game and Watch header image logo is all black and is not quite legible against the dark gray carbon background. The previous Carbon theme used a red logo. Could just reuse that one maybe?

**Comment by bmn001** [comment]
I submitted a pull request to fix.

https://github.com/RetroPie/es-theme-carbon-2021/pull/8

**Comment by cmitu** [comment]
Should be fixed now by https://github.com/RetroPie/es-theme-carbon-2021/pull/17
